version: 2
jobs:
  build:
    docker:
      - image: lakoo/node-gcloud-docker

    working_directory: ~/repo

    steps:
      - checkout

      - run: npm install

      - run: npm run test

      - run: docker -v
