version: 2
jobs:
  build:
    docker:
      - image: lakoo/node-gcloud-docker

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: get-packages
          command: sudo apt-get install build-essential

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test

      - run: docker -v
