version: 2
jobs:
  build:
    docker:
      - image: lakoo/node-gcloud-docker

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}

          - v1-dependencies-

      - run: npm install -g node-zopfli

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run test

      - run: docker -v
