version: 2
jobs:
  build-test:
    docker:
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Run Jest tests
          command: yarn test

  deploy:
    docker:
      - image: shanemckenna23/gcloud-node:0.1.4

    working_directory: ~/repo
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)

      # use a primary image that already has Docker (recommended)
      # or install it during a build like we do here
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      # build and push Docker image
      - run:
          name: Build Docker Image
          command: |
            TAG=0.$CIRCLE_BUILD_NUM
            docker build -t eu.gcr.io/dublin-coach-123/dublin-coach-frontend:$TAG .

      - run:
          name: Install slashes
          command: npm install slashes

      - run:
          name: Generate gcloud auth file
          command: npm run gcloud-auth

      - run:
          name: Authenticate with Google Cloud
          command: gcloud auth activate-service-account circleci@dublin-coach-123.iam.gserviceaccount.com --key-file=config/gcloud.json

      - run:
          name: Push image to Container Registry
          command: |
            TAG=0.$CIRCLE_BUILD_NUM
            gcloud docker -- push eu.gcr.io/dublin-coach-123/dublin-coach-frontend:$TAG

      - run:
          name: Get cluster credentials
          command: gcloud container clusters get-credentials dublin-coach-cluster

      - run:
          name: Deploy new image
          command: kubectl set image deployment/dublin-coach-frontend dublin-coach-frontend=eu.gcr.io/dublin-coach-123/dublin-coach-frontend:$TAG


workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build-test
      - deploy:
          requires:
            - build-test


